---
- name: Add PPA Repository
  sudo: yes
  apt_repository: repo="ppa:nginx/stable"

- name: Update apt
  sudo: yes
  apt: update_cache=yes

- name: Install nginx
  action: apt pkg={{ item }} state=latest
  sudo: yes
  with_items:
      - nginx-full

- name: Copy hub config
  template: src=hub.conf.j2 dest=/etc/nginx/sites-available/{{app_hostname}}.conf
  sudo: yes

- name: Copy nginx config
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  sudo: yes

- name: Create symlink.
  sudo: yes
  file: state=link src=/etc/nginx/sites-available/{{app_hostname}}.conf path=/etc/nginx/sites-enabled/{{app_hostname}}.conf

- name: Reload nginx
  sudo: yes
  service: name=nginx state=restarted