- name: Copy Symfony 2 code style to phpcs
  shell: >
      {{ app_project_root }}/vendor/squizlabs/php_codesniffer/bin/phpcs --config-set installed_paths {{ app_project_root }}/vendor/escapestudios/symfony2-coding-standard