App\Entity\Events:
    type: entity
    table: events
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        person:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
        regAddrKoatuu:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: reg_addr_koatuu
        operCode:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: oper_code
        dReg:
            type: date
            nullable: true
            column: d_reg
        depCode:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: dep_code
        brand:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        model:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        makeYear:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: make_year
        color:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        kind:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        body:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        capacity:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        ownWeight:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: own_weight
        totalWeight:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: total_weight
        nRegNew:
            type: string
            nullable: true
            length: 25
            options:
                fixed: false
            column: n_reg_new
        fuelId:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '11'
            column: fuel_id
        purposed:
            type: string
            nullable: false
            length: 0
            options:
                fixed: false
                default: ЗАГАЛЬНИЙ
    manyToOne:
        operation:
            targetEntity: App\Entity\Operations
            joinColumn:
                name: oper_code
                referencedColumnName: id
        fuel:
            targetEntity: App\Entity\Fuel
            joinColumn:
                name: fuel_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
